### ISSUE TITLE
Update to ember-cli-htmlbars 1.x

### ISSUE THREAD

**Issue by frisco82** [roofstock/ember-cli-data-export#2]
Right now is throwing deprecation warnings, see: ember-cli/ember-cli-htmlbars#77
In fact I am not sure if it is a dependency anymore as I have not found any reference to it in the code.

**Comment by ajcobo** [comment]
Could it be posible to have a version bump?

**Comment by matt-roofstock** [comment]
0.1.27 published to npm. thanks for input and sorry for delay updating.
