### ISSUE TITLE
ember-cli-babel deprecation warnings

### ISSUE THREAD

**Issue by maxwondercorn** [roofstock/ember-cli-data-export#26]
ember-cli-babel < 6.6.0 is now deprecated.  I'm hunting down all the addons generating deprecation warnings

**Comment by maxwondercorn** [comment]
There is also a deprecation warning for ember-select-list for the same thing.  I see that select-list is being used in the addon component that's not documented.  

If that's not a core part of the export service can it be removed and eliminate the need for dependency on ember-select-list?  I can do a PR if you want.

**Comment by Gorzas** [comment]
The current version in master has [ember-cli-babel@6.6.0](https://github.com/begedin/ember-select-list/blob/master/package.json). Could it be a good idea to use that version of the code?

**Comment by AndresCL** [comment]
Did you fix it @maxwondercorn? This still points to 5.1.7

![image](https://user-images.githubusercontent.com/1790792/60972884-7c755280-a2fd-11e9-8efb-e4d05eab090f.png)

**Comment by maxwondercorn** [comment]
@AndresCL I'm no longer using the addon.  I moved the export functionality to the server to reduce bundle sizes.
